
set(GALACTIC_PATH "$ENV{galactic_home}" CACHE PATH "Galactic location")

if(NOT EXISTS "${GALACTIC_PATH}")
	message(FATAL_ERROR "Invalid Galactic path")
endif()

include_directories("${GALACTIC_PATH}/include")

if(WIN32)
	set(GALACTIC_LIBS "${GALACTIC_PATH}/${LIB_DIRECTORY}")
endif()

if(MSVC)
	set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} /LIBPATH:\"${GALACTIC_LIBS}/Debug\"")
	set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LIBPATH:\"${GALACTIC_LIBS}/Release\"")
	set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO} /LIBPATH:\"${GALACTIC_LIBS}/RelWithDebInfo\"")

	set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} /LIBPATH:\"${GALACTIC_LIBS}/Debug\"")
	set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LIBPATH:\"${GALACTIC_LIBS}/Release\"")
	set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO} /LIBPATH:\"${GALACTIC_LIBS}/RelWithDebInfo\"")
endif()
