
if(SUPPORT_WINXP)
	set(SPIDERMONKEY_BUILD esr52)
else()
	set(SPIDERMONKEY_BUILD esr60)
endif()

set(SPIDERMONKEY_PATH "${CMAKE_SOURCE_DIR}/../SpiderMonkey" CACHE PATH "SpiderMonkey location")
include_directories("${SPIDERMONKEY_PATH}/${SPIDERMONKEY_BUILD}/include")

if(WIN32)
	set(SPIDERMONKEY_LIBS "${SPIDERMONKEY_PATH}/${SPIDERMONKEY_BUILD}/Lib/${ENGINE_PLATFORM}")
endif()

if(MSVC)
	set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Debug\"")
	set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Release\"")
	set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Release\"")

	set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Debug\"")
	set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Release\"")
	set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Release\"")
endif()
