
if(SUPPORT_WINXP)
	set(SPIDERMONKEY_BUILD "esr52")
else()
	set(SPIDERMONKEY_BUILD "esr60")
endif()

set(SPIDERMONKEY_PATH "${CMAKE_SOURCE_DIR}/../SpiderMonkey" CACHE PATH "SpiderMonkey location")
include_directories("${SPIDERMONKEY_PATH}/${SPIDERMONKEY_BUILD}/include")

if(WIN32)
	set(SPIDERMONKEY_LIBS "${SPIDERMONKEY_PATH}/${SPIDERMONKEY_BUILD}/Lib/${ENGINE_PLATFORM}")
endif()

if(MSVC)
	set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Debug\"")
	set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Release\"")
	set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Release\"")

	set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Debug\"")
	set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Release\"")
	set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO} /LIBPATH:\"${SPIDERMONKEY_LIBS}/Release\"")
endif()

macro(target_link_spidermonkey NAME)
	if(SUPPORT_WINXP)
		target_link_libraries(${NAME} PRIVATE kernel32 mozjs-52)
	else()
		target_link_libraries(${NAME} PRIVATE kernel32 mozjs-60)
	endif()
endmacro()

macro(install_spidermonkey_to TO)
	install(DIRECTORY "${SPIDERMONKEY_LIBS}/Debug/" DESTINATION "${LIB_DIRECTORY}/Debug/${TO}" CONFIGURATIONS Debug FILES_MATCHING PATTERN "*.dll" PATTERN "*.pdb" PATTERN "plc4*" EXCLUDE PATTERN "plds4*" EXCLUDE)
	install(DIRECTORY "${SPIDERMONKEY_LIBS}/Release/" DESTINATION "${LIB_DIRECTORY}/Release/${TO}" CONFIGURATIONS Release FILES_MATCHING PATTERN "*.dll" PATTERN "*.pdb" PATTERN "plc4*" EXCLUDE PATTERN "plds4*" EXCLUDE)
	install(DIRECTORY "${SPIDERMONKEY_LIBS}/Release/" DESTINATION "${LIB_DIRECTORY}/RelWithDebInfo/${TO}" CONFIGURATIONS RelWithDebInfo FILES_MATCHING PATTERN "*.dll" PATTERN "*.pdb" PATTERN "plc4*" EXCLUDE PATTERN "plds4*" EXCLUDE)
endmacro()
